apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: products-privatejet
  labels:
    app: wso2
spec:
  applicationProtocol: http
  ports:
    - name: prod-ep
      port: 80
      targetPort: 9090
  deploy:
    name: products-pj-service
    dockerImage: pubudu/products:1.0.0
    minReplicas: 2
    maxReplicas: 3
    requestCPU: "60m"
    reqMemory: "32Mi"
    cpuLimit: "120m"
  mode: privateJet