info:
  description: This API contains operations related to online shopping store.
  title: Online-Store-Api
  version: v1.0.0
openapi: 3.0.0
paths:
  /inventory/{productId}:
    get:
      parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: ""
    post:
      parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                payload:
                  type: string
              type: object
        description: Request Body
      responses:
        "200":
          description: ""
  /products:
    get:
      responses:
        "200":
          description: ""
  /products/{productId}:
    get:
      parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: ""
  /review/{productId}:
    get:
      parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: ""
x-wso2-basePath: /storemep/{version}
x-wso2-production-endpoints:
  urls:
  - http://istio-ingressgateway.istio-system/storemep/v1.0.0
